version: 0.2

env:
  variables:
    TF_VERSION: "0.15.5"

phases:
  install:
    commands:
      - cd /usr/bin
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip
      - terraform --version

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR_source_output
      - ls
      #- terraform init -no-color
      #- terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Terraform plan completed on `date`"

artifacts:
  files:
    - tfplan
  name: TerraformPlanFile