version: 0.2

env:
  variables:
    TF_VERSION: "0.15.5"
    CODECOMMIT_REPO_URL: "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/vpc-terra"
    INFRASTRUCTURE_DIRECTORY_PATH: "vpc-terra/VPC"

phases:
  install:
    commands:
      - cd /usr/bin
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip
      - terraform --version

  build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - git clone ${CODECOMMIT_REPO_URL}
      - cd ${INFRASTRUCTURE_DIRECTORY_PATH}
      - terraform init -no-color
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Terraform apply completed on `date`"
      - echo "The infrastructure has been deployed"